[package]
name = "ua-nodeset-generator"
version = "1.2.0"
edition.workspace = true
description = "Generate OPC-UA nodeset from concise description, via Model Design"
publish.workspace = true

[workspace]
members = ["crates/*"]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
anyhow = "1.0.103"
schemars = "1.2.1"

[dependencies]
anyhow.workspace = true
askama = "0.16.0"
duct = "1.1.1"
glob = "0.3.3"
schemars.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
toml = "1.1.2"
urn = "0.7.0"

[dev-dependencies]
trycmd = "1.2.0"
